@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false

abstract class Menu {
    +agregarAccion(Integer,  CapazDeEjecutarAccionMenu)
    +getAccion(Integer) : CapazDeEjecutarAccionMenu
    +Menu()
}

class MenuSalir{
  -ejecutar()
}

class MenuABMCAreasMercado extends Menu{
    +MenuABMCAreasMercado()
    +ejecutar(
    +ejecutarAccion()
}
class MenuABMCEmpresas extends Menu{
    +MenuABMCEmpresas();
    +ejecutar() : Void
    +ejecutarAccion()
}
class MenuABMCUbicaciones extends Menu{
    +MenuABMCUbicaciones();
    +ejecutar() : Void
    +ejecutarAccion()
}
class MenuABMCUsuarios extends Menu{
    +MenuABMCUsuarios();
    +ejecutar() : Void
    +ejecutarAccion()
}
class MenuCrearAreaDeMercado{
    +ejecutar() : Void
}
class MenuCrearCiudad{
    +ejecutar() : Void
}
class MenuCrearEmpresa{
    -Ciudad[] : ciudades
    +ejecutar() : Void
}
class MenuCrearPais {
    +ejecutar() : Void
}
class MenuCrearUsuario {
    +ejecutar() : Void
    +elegirOpcion() : Integer
}
class MenuEliminarAreaDeMercado {
    -AreasMercado[] : areas
    +MenuEliminarAreaDeMercado()
    +ejecutar()
    +elegirOpcion() : Integer
}
class MenuEliminarCiudad {
    -Ciudad[] : ciudades
    +MenuEliminarCiudad()
    +ejecutar() : Void
}
class MenuEliminarEmpresa {
    -Empresa[] : empresas
    +MenuEliminarEmpresa()
    +ejecutar()
}
class MenuEliminarUsuario {
    +ejecutar()
    +elegirUsuario()
}
class MenuModificarAreaDeMercado {
    -AreasMercado[] : areas
    +MenuModificarAreaDeMercado()
    +ejecutar()
    +seleccionarAreaMercado(AreasMercado[] areaMercado) : Integer
}
class MenuModificarCiudad {
    -Ciudad[]] : ciudades
    -Pais[] : paises
    +MenuModificarCiudad()
    +ejecutar()
}
class MenuModificarEmpresa {
    -Ciudad[] : ciudades
    -Pais[] : paises
    -Ciudad[] : ciudadesDeEmpresa
    -AreasMercado[] : areas
    +MenuModificarEmpresa()
    +ejecutar()
}
class MenuModificarPais {
    -Pais[] : paises
    +MenuModificarPais()
    +ejecutar()
    +seleccionarPais()
}
class MenuModificarUsuario {
    +MenuModificarUsuario()
    +ejecutar()
    +elegirUsuario() : Integer
}
class MenuPrincipalAdmin {
    +MenuPrincipalAdmin()
    +ejecutar()
    +ejecutarAccion(Integer)
}
class MenuPrincipalNoAdmin {
    +MenuPrincipalNoAdmin()
    +ejecutar()
    +ejecutarAccion(Integer)
}
class MenuVendedorCaptado {
    +ejecutar()
}

interface CapazDeEjecutarAccionMenu <<interface>>{
    +ejecutar()
}

Menu -.|> CapazDeEjecutarAccionMenu
MenuCrearAreaDeMercado --.|> CapazDeEjecutarAccionMenu
MenuCrearCiudad --.|> CapazDeEjecutarAccionMenu
MenuCrearEmpresa --.|> CapazDeEjecutarAccionMenu
MenuCrearPais --.|> CapazDeEjecutarAccionMenu
MenuCrearUsuario ---.|> CapazDeEjecutarAccionMenu
MenuEliminarAreaDeMercado ---.|> CapazDeEjecutarAccionMenu
MenuEliminarCiudad ---.|> CapazDeEjecutarAccionMenu
MenuEliminarEmpresa ---.|> CapazDeEjecutarAccionMenu
MenuEliminarUsuario ---.|> CapazDeEjecutarAccionMenu
MenuModificarAreaDeMercado ---.|> CapazDeEjecutarAccionMenu
MenuModificarCiudad ---.|> CapazDeEjecutarAccionMenu
MenuModificarEmpresa --.|> CapazDeEjecutarAccionMenu
MenuModificarPais --.|> CapazDeEjecutarAccionMenu
MenuModificarUsuario --.|> CapazDeEjecutarAccionMenu
MenuPrincipalAdmin -.|> CapazDeEjecutarAccionMenu
MenuPrincipalNoAdmin -.|> CapazDeEjecutarAccionMenu
MenuVendedorCaptado -.|> CapazDeEjecutarAccionMenu
MenuSalir -.|> CapazDeEjecutarAccionMenu

Menu --> "*" CapazDeEjecutarAccionMenu : acciones
@enduml
