@startuml
class SistemaDeGestion{
+mostrarMenu() : Integer
+run() : void
}

class BaseDatosHolding{
-autenticarUsuario(String,String) : Usuario
+iniciarSesion() : Usuario
}

abstract Usuario{
-{static} CONTADOR
-codigoUsuario : Integer
-nombre : String
-direccion : String
-pass : String

+proceder() : void
+validarNombre() : Boolean
+validarPass() : Boolean
+mostrarInformacionUsuario() : void
}

class Vendedor extends Usuario{
    -nombre : String
    -direccion : String
    -fechaCaptado : Date
    +Vendedor(String,String,String,Date)
    +captarVendedor(Vendedor) : Void
    +contadorVendedoresCapt() : Integer
    +proceder() : void
    +mostrarInformacionUsuario() : void

}

class Empresa{
    -nombre : String
    -fechaEntrada : Date
    -facturacionAnual : Double
    +Empresa(String,Date,Double)
    +displayInfo() : String
}

class AreaMercado {
    -nombre : String
    -descripcion : String

    +AreaMercado()
    +mostrarInformacion() : Void
}

class Asesor extends Usuario{
-nombre : String
-direccion : String
-titulacion : String
-fechasInicio : List
+asesorarEmpresa(Empresa)
+cubrirAreaMercado(AREAS_MERCADO) : void
+mostrarInformacionUsuario() : void
}

class VinculacionAsesorEmpresa{
    -fechaInicio : Date

    +VinculacionAsesorEmpresa()
    +getAsesor() : Asesor
    +getFechaInicio() : Date
}

class Admin extends Usuario{
-nombre : String
-direccion : String
-fechaInicio : Date
+crearVendedor() : void
+crearAsesor() : void
+crearEmpresa(): void
+crearPais() : void
+proceder() : void
+mostrarMenu() : Integer
+mostrarInformacionUsuario() : void
}

class Pais{
    -nombre : String
    -pbi : Double
    -numHabitantes : double

    +Pais(String,double,double)
    +hacerSede(Empresa) : void
    -eliminarSede(Empresa) : void
}

class Ciudad{
    -nombre: String
    +Ciudad(String,Pais);
    +esIgual(Ciudad) : Boolean
}


interface CapazDeVisualizarMenu <<interface>>{
    +{abstract} mostrarMenu() : void
}

interface CapazDeMostrarSuInformacion <<interface>>{
    +{abstract} mostrarInformacion() : void
}

SistemaDeGestion -> BaseDatosHolding : "baseDeDatos"
SistemaDeGestion -.|> CapazDeVisualizarMenu
BaseDatosHolding -> "*" Usuario : usuarios
BaseDatosHolding -> "*" Empresa : empresas
Usuario -.|> CapazDeVisualizarMenu
Usuario -.|> CapazDeMostrarSuInformacion
Vendedor "*" o--> Empresa : vendedores
Vendedor -> "*" Vendedor : vendedoresCaptados

Empresa "1"--> "*" AreaMercado : areasMercado
Empresa -.|> CapazDeMostrarSuInformacion
Empresa <- Ciudad : sede
VinculacionAsesorEmpresa "*" <- Empresa: asesores
Ciudad <-o Pais : paisOrigen
Ciudad -> "*" Empresa : ciudades

Asesor "*"-> "*" AreaMercado : mercadosCubiertos
Asesor <-o VinculacionAsesorEmpresa : asesor


@enduml