@startuml
class SistemaDeGestion{
+mostrarMenu() : Integer
+run() : void
}

class BaseDatosHolding{
-autenticarUsuario(Integer,String) : Usuario
+iniciarSesion() : Usuario
}

abstract Usuario{
-{static} CONTADOR
-codigoUsuario : Integer
-nombre : String
-direccion : String
-pass : String

+proceder() : void
+validarNombre() : Boolean
+validarPass() : Boolean
+mostrarInformacionUsuario() : void
+getCodigoUsuario() : Integer
}

class Vendedor extends Usuario{
    -nombre : String
    -direccion : String
    -fechaCaptado : Date
    +Vendedor(String,String,String,Date)
    +captarVendedor(Vendedor) : Void
    +contadorVendedoresCapt() : Integer
    +proceder() : void
    +mostrarInformacionUsuario() : void

}

class Empresa{
    -nombre : String
    -fechaEntrada : Date
    -facturacionAnual : Double
    -contador : Integer
    -codigoEmpresa : Integer
    +Empresa(String,Date,Double)
    +displayInfo() : String
}

class AreaMercado {
    -nombre : String
    -descripcion : String

    +AreaMercado()
    +mostrarInformacion() : Void
}

class Asesor extends Usuario{
-nombre : String
-direccion : String
-titulacion : String
-fechasInicio : List
+asesorarEmpresa(Empresa)
+cubrirAreaMercado(AREAS_MERCADO) : void
+mostrarInformacionUsuario() : void
}

class VinculacionAsesorEmpresa{
    -fechaInicio : Date

    +VinculacionAsesorEmpresa()
    +getAsesor() : Asesor
    +getFechaInicio() : Date
}

class Admin extends Usuario{
-nombre : String
-direccion : String
-fechaInicio : Date
+crearVendedor() : void
+crearAsesor() : void
+crearEmpresa(): void
+crearPais() : void
+proceder() : void
+mostrarMenu() : Integer
+mostrarInformacionUsuario() : void
}

class Pais{
    -nombre : String
    -pbi : Double
    -numHabitantes : double

    +Pais(String,double,double)
    +hacerSede(Empresa) : void
    -eliminarSede(Empresa) : void
}

class Ciudad{
    -nombre: String
    +Ciudad(String,Pais);
    +esIgual(Ciudad) : Boolean
}

interface CapazDeVisualizarMenu <<interface>>{
    +{abstract} mostrarMenu() : void
}

interface CapazDeMostrarSuInformacion <<interface>>{
    +{abstract} mostrarInformacion() : void
}

interface CapazDeEjecutarAccionMenu <<interface>>{
    +ejecutar() : void
}

abstract class MenuSuper{
    -acciones : Hashmap<Integer, CapazDeEjecutarAccionMenu>
    +agregarAccion(Integer,  CapazDeEjecutarAccionMenu) : void
    +getAccion(Integer) : CapazDeEjecutarAccionMenu
    }


class MenuABMCAreasMercado extends MenuSuper{
    +ejecutar() : void
}

class MenuABMCUsuarios extends MenuSuper{
    +ejecutar() : void
    +ejecutarAccion(Integer) : void
}

class MenuABMCEmpresas extends MenuSuper{
    +ejecutar() : void
    +ejecutarAccion(Integer) : void
}

class MenuABMCUbicaciones extends MenuSuper{
    +ejecutar() : void
}


class MenuPrincipalAdmin extends MenuSuper{
    +ejecutar() : void
    +ejecutarAccion(Integer) : void
}

class MenuPrincipalAsesor extends MenuSuper{
    +ejecutar() : void
    +ejecutarAccion(Integer) : void
}

class MenuPrincipalVendedor extends MenuSuper{
    +ejecutar() : void
    +ejecutarAccion(Integer) : void
}


class MenuCrearUsuario extends CapazDeEjecutarAccionMenu{
    +ejecutar() : void
}

class MenuVendedorCaptado extends CapazDeEjecutarAccionMenu{
      +ejecutar() : void
}

class MenuEliminarUsuario extends CapazDeEjecutarAccionMenu{
    +ejecutar() : void
}

class MenuModificarUsuario extends CapazDeEjecutarAccionMenu{
    +ejecutar() : void
}


SistemaDeGestion -> BaseDatosHolding : "baseDeDatos"
SistemaDeGestion -.|> CapazDeVisualizarMenu
BaseDatosHolding -> "*" Usuario : usuarios
BaseDatosHolding -> "*" Empresa : empresas
Usuario -.|> CapazDeVisualizarMenu
Usuario -.|> CapazDeMostrarSuInformacion
Vendedor "*" o--> Empresa : vendedores
Vendedor -> "*" Vendedor : vendedoresCaptados

Empresa "1"--> "*" AreaMercado : areasMercado
Empresa -.|> CapazDeMostrarSuInformacion
Empresa <- Ciudad : sede
VinculacionAsesorEmpresa "*" <- Empresa: asesores
Ciudad <-o Pais : paisOrigen
Ciudad -> "*" Empresa : ciudades

Asesor "*"-> "*" AreaMercado : mercadosCubiertos
Asesor <-o VinculacionAsesorEmpresa : asesor

Admin -.|> MenuPrincipalAdmin
MenuSuper -.|> CapazDeEjecutarAccionMenu
Asesor -.|> MenuPrincipalAsesor
Vendedor -.|> MenuPrincipalVendedor


@enduml