@startuml
class MenuPrincipal implements CapazDeEjecutarUnaAccionMenu{
    -acciones : HashMap
    +agregarAccion(Integer,CapazDeEjecutarUnaAccionMenu) : void
    +ejecutarAccion(Integer) : void
}

class MenuVerInformacion implements CapazDeEjecutarUnaAccionMenu{
    +ejecutarAccion(Integer): void
}

class MenuABMCUsuarios implements CapazDeEjecutarUnaAccionMenu{
    +ejecutarAccion(Integer): void
}

class MenuABMCEmpresa implements CapazDeEjecutarUnaAccionMenu{
    +ejecutarAccion(Integer): void
}

class MenuABMCAreaMercado implements CapazDeEjecutarUnaAccionMenu{
    +ejecutarAccion(Integer): void
}

class MenuABMCCiudad implements CapazDeEjecutarUnaAccionMenu{
    +ejecutarAccion(Integer): void
}

interface CapazDeEjecutarUnaAccionMenu{
    +ejecutar() : void
}
@enduml